<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="UCSB Data Day – Southern California Consortium for Data Science">
<meta name="dcterms.date" content="2026-03-07">

<title>Datathon: Hands-on Afternoon Activity</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-79108a0fc1995748cbd19a5b0e3e3e7c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body>

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p><img src="SCCDS.png" class="img-fluid"></p>
</div></div>
        
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="datathon.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Datathon: Hands-on Afternoon Activity</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>UCSB Data Day – Southern California Consortium for Data Science </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="channel-islands" class="level2">
<h2 class="anchored" data-anchor-id="channel-islands">Channel Islands</h2>
<p>The <strong>Channel Islands</strong> are a chain of eight islands located off the southern coast of California in the Pacific Ocean. They are known for their stunning natural beauty, ecological richness, and deep cultural history.</p>
<section id="the-eight-channel-islands-north-to-south" class="level3">
<h3 class="anchored" data-anchor-id="the-eight-channel-islands-north-to-south">The Eight Channel Islands (North to South)</h3>
<ol type="1">
<li><p><strong>San Miguel Island</strong></p></li>
<li><p><strong>Santa Rosa Island</strong></p></li>
<li><p>Santa Cruz Island</p></li>
<li><p>Anacapa Island</p></li>
<li><p>Santa Barbara Island</p></li>
<li><p>San Nicolas Island</p></li>
<li><p>San Clemente Island</p></li>
<li><p>Santa Catalina Island</p></li>
</ol>
<p>Below we will only consider the two bolded islands: SMI and SRI</p>
</section>
<section id="channel-islands-national-park" class="level3">
<h3 class="anchored" data-anchor-id="channel-islands-national-park"><a href="https://www.nps.gov/chis/index.htm">Channel Islands National Park</a></h3>
<ul>
<li>Includes <strong>five islands</strong>: <em>San Miguel</em>, <em>Santa Rosa</em>, <em>Santa Cruz</em>, <em>Anacapa</em>, and <em>Santa Barbara</em>.</li>
<li>Sometimes called the “Galápagos of North America” for its rich biodiversity and many <strong>endemic species</strong>.</li>
<li>Accessible only by <em>boat or small plane</em>.</li>
<li>Ideal for hiking, kayaking, camping, and wildlife observation.</li>
</ul>
</section>
<section id="cultural-and-historical-significance" class="level3">
<h3 class="anchored" data-anchor-id="cultural-and-historical-significance">Cultural and Historical Significance</h3>
<ul>
<li>Originally inhabited by <a href="https://www.nps.gov/chis/learn/historyculture/nativeinhabitants.htm#:~:text=With%20a%20current%20population%20nearly,organized%20Chumash%20tribal%20groups%20exist"><strong>Chumash</strong> and <strong>Tongva</strong></a> indigenious groups for thousands of years.</li>
<li>Home to important archaeological and cultural heritage sites.</li>
</ul>
</section>
</section>
<section id="island-fox-urocyon-littoralis" class="level2">
<h2 class="anchored" data-anchor-id="island-fox-urocyon-littoralis">Island Fox (<em>Urocyon littoralis</em>)</h2>
<p>The <strong>island fox</strong> is a small, charismatic canid species <em>endemic</em> to six of the eight <em>Channel Islands</em> off the coast of southern California. It’s one of the best examples of <strong>island dwarfism</strong>, having evolved from the mainland gray fox (<em>Urocyon cinereoargenteus</em>) to become significantly smaller.</p>
<p>In the <strong>1990s</strong>, several island fox populations faced <strong>near extinction</strong> due to golden eagle predation, canine distemper virus, and habitat degradation. The island fox was listed as endangered in 2004. Recovery efforts of the island fox included removal of golden eagles, vaccination and captive breeding programs, reintroduction of native bald eagles, and habitat restoration.</p>
</section>
<section id="hands-on-activity" class="level2">
<h2 class="anchored" data-anchor-id="hands-on-activity">Hands-on Activity</h2>
<p>First, please go through the <a href="#intro">Introduction</a> which includes data preparation and some basics of how this dataset looks like.<br>
Depending on your level of comfort, work then on either <a href="#part1">Part I</a> (Easier) or <a href="#part2">Part II</a> (Advanced) challenges. If you’re ambitious, you can do both, or even come up with your own questions.</p>
<p>For both groups, we have an <strong>Optional Share-Out</strong> during the last portion of the Datathon: participants can present one result of their choosing to the group. If you would like to do so, make sure to invest time in making a nice plot: play around with the plot <code>theme</code>, font sizes, color palettes, labels and layout. Google (via its automatic Gemini search results) is a good tool to dive deep into the myriad ggplot customization options. Note that <em>everything</em> in the plot can be customized to your choosing, that is (one of) the power of using a statistical package.</p>
<p>As a start, you will investigate one of the two sections, <a href="#fox-weight">Fox Weight</a> or <a href="#fox-rs">Fox Reproductive Status</a>. Follow the guidelines in the section of your choice and complete one of the challenges. <strong>You may also analyze the data in any other way or work on the other section, but it is not necessary.</strong></p>
</section>
<section id="intro" class="level2">
<h2 class="anchored" data-anchor-id="intro">Data and Prep</h2>
<p>The data provided is part of an ongoing longitudinal study of island foxes from 2014 to 2016 of trap monitoring. This resulted in collection of 4,975 recorded trap observations, which may have contained a fox or not. Other information collected were Sex, Age Class, Weight, Body Condition, Reproductive Status, and Vaccinations. Information on the data collected can be found in the <a href="https://github.com/mludkov/UCSB_Data_Day_2026/blob/gh-pages/data_for_datathon_2014_2016.csv">Databook</a>.</p>
<section id="loading-packages" class="level3">
<h3 class="anchored" data-anchor-id="loading-packages">Loading Packages</h3>
<p>The <code>tidyverse</code> suite is a collection of data analysis packages:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
</section>
<section id="loading-data" class="level3">
<h3 class="anchored" data-anchor-id="loading-data">Loading Data</h3>
<p>We will load the data into the R workspace using the <code>read_csv</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Need to modify to load the file from the location where you downloaded it</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data_for_datathon_2014_2016.csv"</span>)) <span class="co"># Loads the Data Set into the object df</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 4975 Columns: 16
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (9): Island, GridCode, TrapResult, Pittag, CaptureType, Sex, Weight_uni...
dbl  (6): SamplingYear, NightNumber, TrapNumber, AgeClass, Weight, BodyCondi...
dttm (1): TrapDate

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="cleaning-data" class="level3">
<h3 class="anchored" data-anchor-id="cleaning-data">Cleaning Data</h3>
<section id="renaming-categories" class="level4">
<h4 class="anchored" data-anchor-id="renaming-categories">Renaming Categories</h4>
<p>Looking at the <a href="https://github.com/mludkov/UCSB_Data_Day_2026/blob/gh-pages/IslandFoxes_codebook.pdf">Codebook</a>, the variables <code>Vaccinations</code>, <code>ReproductiveStatus</code> and <code>BodyCondition</code> are coded in interesting ways. In <code>Vaccinations</code>, missing values (<code>NA</code>) are considered as not vaccinated; therefore, changing the missing to “NV” will ensure that they are correctly classified. In <code>ReproductiveStatus</code>, the missing values (<code>NA</code>) indicate unknown reproductive status. In <code>BodyCondition</code>, the numerical values 1, 2, 3, 4, and 5, represent a condition. To make the condition easier, we will convert them to the categories. Run the code below to alter them:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> <span class="fu">mutate</span>( <span class="co"># Will change the variables in the df data set</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">Vaccinations =</span> <span class="fu">case_when</span>(<span class="fu">is.na</span>(Vaccinations) <span class="sc">~</span> <span class="st">"NV"</span>, <span class="at">.default =</span> Vaccinations), <span class="co"># Reclassifies Missing Data in Vaccination as "N" per code book.</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">ReproductiveStatus =</span> <span class="fu">case_when</span>(<span class="fu">is.na</span>(ReproductiveStatus) <span class="sc">~</span> <span class="st">"UN"</span>, <span class="at">.default =</span> ReproductiveStatus), <span class="co"># Reclassifies Missing Data in Vaccination as "N" per code book.</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">BodyCondition =</span> <span class="fu">case_when</span>( <span class="co"># Begins to modify BodyCondition</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">as.character</span>(BodyCondition) <span class="sc">==</span> <span class="st">"1"</span> <span class="sc">~</span> <span class="st">"emaciated"</span>, <span class="co"># Changes 1 to emaciated</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">as.character</span>(BodyCondition) <span class="sc">==</span> <span class="st">"2"</span> <span class="sc">~</span> <span class="st">"thin"</span>, <span class="co"># Changes 2 to thin</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        <span class="fu">as.character</span>(BodyCondition) <span class="sc">==</span> <span class="st">"3"</span> <span class="sc">~</span> <span class="st">"healthy wild"</span>, <span class="co"># Changes 3 to healthy wild </span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="fu">as.character</span>(BodyCondition) <span class="sc">==</span> <span class="st">"4"</span> <span class="sc">~</span> <span class="st">"extra fat reserves"</span>, <span class="co"># Changes 4 to Extra Fat Reserve</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">as.character</span>(BodyCondition) <span class="sc">==</span> <span class="st">"5"</span> <span class="sc">~</span> <span class="st">"extreme fat reserves"</span> <span class="co"># Changes 5 to Extreme Fat Reserves</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="missing-values" class="level4">
<h4 class="anchored" data-anchor-id="missing-values">Missing Values</h4>
<p>Several variables in the data set may be missing. Using the <code>summary()</code>, we can determine which variables have missing values by looking at the “NA’s” category.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Island           SamplingYear    GridCode        
 Length:4975        Min.   :2014   Length:4975       
 Class :character   1st Qu.:2014   Class :character  
 Mode  :character   Median :2015   Mode  :character  
                    Mean   :2015                     
                    3rd Qu.:2016                     
                    Max.   :2016                     
                                                     
    TrapDate                    NightNumber      TrapNumber    
 Min.   :2014-07-16 00:00:00   Min.   :1.000   Min.   :  1.00  
 1st Qu.:2014-08-24 00:00:00   1st Qu.:2.000   1st Qu.:  4.00  
 Median :2015-08-12 00:00:00   Median :3.000   Median :  8.00  
 Mean   :2015-08-25 01:31:27   Mean   :3.392   Mean   : 18.87  
 3rd Qu.:2016-08-18 00:00:00   3rd Qu.:5.000   3rd Qu.: 11.00  
 Max.   :2016-11-30 00:00:00   Max.   :6.000   Max.   :108.00  
                                                               
  TrapResult           Pittag          CaptureType            Sex           
 Length:4975        Length:4975        Length:4975        Length:4975       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
    AgeClass         Weight       Weight_units       BodyCondition     
 Min.   :0.000   Min.   :  0.72   Length:4975        Length:4975       
 1st Qu.:1.000   1st Qu.:  1.73   Class :character   Class :character  
 Median :1.000   Median :  2.02   Mode  :character   Mode  :character  
 Mean   :1.557   Mean   : 49.49                                        
 3rd Qu.:3.000   3rd Qu.:  2.30                                        
 Max.   :4.000   Max.   :910.00                                        
 NA's   :2840    NA's   :2808                                          
 ReproductiveStatus Vaccinations      
 Length:4975        Length:4975       
 Class :character   Class :character  
 Mode  :character   Mode  :character  
                                      
                                      
                                      
                                      </code></pre>
</div>
</div>
<p>We notice that the variables <code>AgeClass</code>, <code>Weight</code>, and <code>BodyCondition</code> have missing values. <strong>For this analysis, we will remove the missing values (<code>NA</code>).</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">drop_na</span>(df, AgeClass, Weight, BodyCondition) <span class="co"># Removes the missing values (NA) using the variables AgeClass, Weight, and BodyCondition</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>After cleaning the data, this should result in 1,967 recorded foxes!</strong> This is the dataset that we will be using for the rest of this activity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1967</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="part1" class="level2">
<h2 class="anchored" data-anchor-id="part1">Part I:</h2>
<section id="fox-weight" class="level3">
<h3 class="anchored" data-anchor-id="fox-weight">Fox Weight Analysis</h3>
<p>Imagine you’re a field biologist tracking animal health across the remote Santa Rosa and San Miguel Islands. You’ve noticed that some animals seem heavier in certain years—but is it just your imagination, or is there a real trend?</p>
<p>The <code>Weght</code> variable contains information of the Fox’s weight in kilograms. Let’s start by calculating the mean weight and standard deviation of weight using <code>mean()</code> and <code>sd()</code> functions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mean_weight<span class="ot">&lt;-</span><span class="fu">mean</span>(df<span class="sc">$</span>Weight)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>sd_weight<span class="ot">&lt;-</span><span class="fu">sd</span>(df<span class="sc">$</span>Weight)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>mean_weight</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.940275</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>sd_weight <span class="co">#printing the values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4140872</code></pre>
</div>
</div>
<p>We see that mean weight of a fox is about 1.9 kg (which is about 4 pounds) with standard deviation about .41 kg.</p>
<p>We use the <code>table()</code> and <code>prop.table()</code> functions to get the frequencies and proportions for the <code>Sex</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>count_df <span class="ot">&lt;-</span> <span class="fu">table</span>(df<span class="sc">$</span>Sex) <span class="co"># Using the 'Sex' variable from the `df` data set, we count the frequencies of each category with the table function and storing it in rs_df.</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>count_df <span class="co"># Printing out the contents of "rs_df"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Female   Male 
   923   1044 </code></pre>
</div>
</div>
<p>Using the <code>table()</code> function, we can see that there were 923 female and 1044 male Foxes captured.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(count_df) <span class="co"># Computing the Proportions of "rs_df"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Female      Male 
0.4692425 0.5307575 </code></pre>
</div>
</div>
<p>The <code>prop.table()</code> function shows the respective percentages: there are slightly more male Foxes (about 53%) vs.&nbsp;female Foxes (about 47%).</p>
<p>We can visualize the data using the <code>ggplot</code> functions. Namely we build a bar plot that shows those above counts visually (with more Male than Female foxes):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df) <span class="sc">+</span> <span class="co"># Setting up the data to create a plot.</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(Sex)) <span class="sc">+</span> <span class="co"># Creating a bar chart based on the variable "ReproductiveStatus" </span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>), <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="datathon_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="weight-vs-sex" class="level3">
<h3 class="anchored" data-anchor-id="weight-vs-sex">Weight vs Sex</h3>
<p>Let’s visualize the variable <code>Weight</code> and <code>Sex</code> with a boxplot using <code>ggplot</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Sex, <span class="at">y =</span> Weight)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Boxplot of Weight by Sex"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Sex"</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Weight"</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="datathon_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the box plot we see that male Foxs tend to be slightly <em>heavier</em> than female Foxes.</p>
<p>We can use <code>group_by()</code> function to separate male from female population and calculate means and standard deviations separately:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>weight_summary <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Sex) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_weight =</span> <span class="fu">mean</span>(Weight),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_weight =</span> <span class="fu">sd</span>(Weight),</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>weight_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  Sex    mean_weight sd_weight
  &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;
1 Female        1.88     0.386
2 Male          1.99     0.431</code></pre>
</div>
</div>
<p>This table confirms that male Foxes are slightly heavier, with mean weight of about 1.99 kg, than female Foxes, whose mean weight is about 1.88 kg. Standard deviations are also slightly higher for male Foxes.</p>
<section id="weight-vs-sex-over-time" class="level4">
<h4 class="anchored" data-anchor-id="weight-vs-sex-over-time">Weight vs Sex over time</h4>
<p>To see weight vs sex trend over time we can use <code>group_by()</code> and <code>ggplot</code> functions again:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>weight_summary_yearly <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Sex, SamplingYear) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_weight =</span> <span class="fu">mean</span>(Weight, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_weight =</span> <span class="fu">sd</span>(Weight, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="co">#group the data by Sex and Year and calculate mean and standard deviation of weight</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>weight_summary_yearly</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  Sex    SamplingYear mean_weight sd_weight
  &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;
1 Female         2014        1.95     0.362
2 Female         2015        1.85     0.409
3 Female         2016        1.86     0.373
4 Male           2014        2.08     0.405
5 Male           2015        1.95     0.451
6 Male           2016        1.99     0.419</code></pre>
</div>
</div>
<p>From the table we see a downward trend in weight for both females and males across years. Let’s plot it on the graph:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(weight_summary_yearly, <span class="fu">aes</span>(<span class="at">x =</span> SamplingYear, <span class="at">y =</span> mean_weight)) <span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean_weight <span class="sc">-</span> sd_weight,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> mean_weight <span class="sc">+</span> sd_weight), <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Sex) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Average Weight by Year and Sex"</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean Weight"</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Year"</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="datathon_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Weight vs Sex over time by Island
</div>
</div>
<div class="callout-body-container callout-body">
<p>Here is a first question for you to answer: do the foxes on different islands have the same weight? Is there an island where the foxes are <strong>significantly</strong> heavier than others? To conduct such analysis, you can filter by different <code>Islands</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Santa Rosa Fox population </span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>SR_df<span class="ot">&lt;-</span><span class="fu">filter</span>(df,Island<span class="sc">==</span><span class="st">"SRI"</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co">#San Miguel Fox population</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>SM_df<span class="ot">&lt;-</span><span class="fu">filter</span>(df,Island<span class="sc">==</span><span class="st">"SMI"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
</section>
<section id="questions-to-try-out" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-try-out">Questions to Try Out</h3>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vaccinations
</div>
</div>
<div class="callout-body-container callout-body">
<p>Do vaccinated foxes have a different weight compared to unvaccinated ones? To answer this, study the relationship between <code>Weight</code> and <code>Vaccinations</code></p>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Body Condition
</div>
</div>
<div class="callout-body-container callout-body">
<p>The dataset has a variable called <code>BodyCondition</code>. What proportion of foxes are well nourished? Do some islands have a larger proportion of “fat” foxes than others? How does <code>BodyCondition</code> connect with <code>Weight</code>? For the latter, you could look into scatter plots.</p>
</div>
</div>
</section>
<section id="fox-rs" class="level3">
<h3 class="anchored" data-anchor-id="fox-rs">Fox Reproductive Status Analysis</h3>
<p>The <code>ReproductiveStatus</code> variable contains information of the Fox’s reproductive status when captures. This data is recorded as “N” (Not actively reproductive), “L” (Lactating), “SL” (Signs of Lactating), and “TD” (Testes Distended).</p>
<p>We will use the <code>table()</code> and <code>prop.table()</code> function to get the frequencies and proportions for the <code>ReproductiveStatus</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>rs_df <span class="ot">&lt;-</span> <span class="fu">table</span>(df<span class="sc">$</span>ReproductiveStatus) <span class="co"># Using the 'ReproductiveStatus' variable from the `df` data set, we count the frequencies of each category with the table function and storing it in rs_df.</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>rs_df <span class="co"># Printing out the contents of "rs_df"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   L   SL   TD   UN 
  18  244 1030  675 </code></pre>
</div>
</div>
<p>Using the <code>table()</code> function, we can see that there are 3 common reproductive statuses by Fox: “L” at 18, “SL” at 244, “TD” at 1030, and “UN” at 675.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(rs_df) <span class="co"># Computing the Proportions of "rs_df"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          L          SL          TD          UN 
0.009150991 0.124046772 0.523640061 0.343162176 </code></pre>
</div>
</div>
<p>Using the <code>prop.table()</code> function, we can see that that the most common status is “TD” at 52.4% and the least common is “L” at the 0.9%. Both “SL” and “UN” represent 12.4% and 34.3% of the data, respectively. In barplot format we have:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df) <span class="sc">+</span> <span class="co"># Setting up the data to create a plot.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(ReproductiveStatus)) <span class="co"># Creating a bar chart based on the variable "ReproductiveStatus"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="datathon_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="sex-and-reproductive-status" class="level4">
<h4 class="anchored" data-anchor-id="sex-and-reproductive-status">Sex and Reproductive Status</h4>
<p>Let’s compare the frequencies between the variables <code>Sex</code> and <code>Reproductive Status</code>. We will be using the same <code>table()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>xy_df <span class="ot">&lt;-</span> <span class="fu">table</span>(df<span class="sc">$</span>ReproductiveStatus, df<span class="sc">$</span>Sex)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the variables "ReproductiveStatus" and "Sex" from the "df" data set</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the table function to compute the crosstabs</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Store the results in the xy_df object</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>xy_df <span class="co"># Print results out</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    
     Female Male
  L      18    0
  SL    244    0
  TD      0 1030
  UN    661   14</code></pre>
</div>
</div>
<p>The results show that certain categorical combinations between <code>ReproductiveStatus</code> and <code>Sex</code> are 0, which is to be expected. The category “UN” is found in both Male and Female foxes. Looking at Female foxes, The most common type is “UN”, followed by “SL”. For Male foxes, the most common type was “TD”.</p>
<p>Let’s find the proportions for each the combination of the variables using the <code>prop.table()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(xy_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    
          Female        Male
  L  0.009150991 0.000000000
  SL 0.124046772 0.000000000
  TD 0.000000000 0.523640061
  UN 0.336044738 0.007117438</code></pre>
</div>
</div>
<p>We can see that 52.4% of the data are Male and “TD” foxes, 33.6% of the data are Female and “UN” foxes, and 12.4% of the data are Female and “SL” foxes. To visualize how the variable <code>ReproductiveStatus</code> and <code>Sex</code> related to each other we use a stacked bar plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(Sex, <span class="at">fill =</span> ReproductiveStatus)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>), <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="datathon_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot indicate which categories are most dominant in each sex. We can see that the most dominant reproductive status in Male foxes is testes distended. For Female foxes, we can see that the most common reproductive status is Unknown.</p>
</section>
</section>
<section id="challenges" class="level3">
<h3 class="anchored" data-anchor-id="challenges">Challenges</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Age Class
</div>
</div>
<div class="callout-body-container callout-body">
<p>How does <code>ReproductiveStatus</code> relate to <code>AgeClass</code> (how old is the fox), to <code>Vaccinations</code>, and to <code>Capture Type</code>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Skunking
</div>
</div>
<div class="callout-body-container callout-body">
<p>How many skunks were caught each year? Are there more skunks on some island than others? (Look at <code>TrapResult</code>. Note that some skunks were caught but escaped, see the different possible values of this field!)</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Fox Ages
</div>
</div>
<div class="callout-body-container callout-body">
<p>What is the Age distribution of the foxes? How many foxes are less than 1 year old? Does this vary by year or by island? (Look at <code>AgeClass</code>. Notice that it’s a numeric variable)</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Trap Effectiveness
</div>
</div>
<div class="callout-body-container callout-body">
<p>Analyze how often do the traps work (expressed as a success percentage). Namely, which Island and which Years yield the most foxes?</p>
</div>
</div>
</section>
</section>
<section id="part2" class="level2">
<h2 class="anchored" data-anchor-id="part2">Part 2: For More Advanced Participants</h2>
<section id="tracking-foxes" class="level3">
<h3 class="anchored" data-anchor-id="tracking-foxes">Tracking Foxes</h3>
<p>Each fox gets a unique Pit Tag. This <code>Pittag</code> field allows to track a specific fox across time. For example, let’s consider fox with tag 989001000124022. It shows up in the following records:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(df[<span class="fu">which</span>(df<span class="sc">$</span>Pittag<span class="sc">==</span><span class="dv">989001000124022</span>),])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Island</th>
<th style="text-align: right;">SamplingYear</th>
<th style="text-align: left;">GridCode</th>
<th style="text-align: left;">TrapDate</th>
<th style="text-align: right;">NightNumber</th>
<th style="text-align: right;">TrapNumber</th>
<th style="text-align: left;">TrapResult</th>
<th style="text-align: left;">Pittag</th>
<th style="text-align: left;">CaptureType</th>
<th style="text-align: left;">Sex</th>
<th style="text-align: right;">AgeClass</th>
<th style="text-align: right;">Weight</th>
<th style="text-align: left;">Weight_units</th>
<th style="text-align: left;">BodyCondition</th>
<th style="text-align: left;">ReproductiveStatus</th>
<th style="text-align: left;">Vaccinations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SRI</td>
<td style="text-align: right;">2016</td>
<td style="text-align: left;">QC</td>
<td style="text-align: left;">2016-08-03</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FOX</td>
<td style="text-align: left;">989001000124022</td>
<td style="text-align: left;">N</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.55</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">healthy wild</td>
<td style="text-align: left;">UN</td>
<td style="text-align: left;">RD</td>
</tr>
<tr class="even">
<td style="text-align: left;">SRI</td>
<td style="text-align: right;">2016</td>
<td style="text-align: left;">QC</td>
<td style="text-align: left;">2016-08-05</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">FOX</td>
<td style="text-align: left;">989001000124022</td>
<td style="text-align: left;">R2</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.05</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">healthy wild</td>
<td style="text-align: left;">UN</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SRI</td>
<td style="text-align: right;">2016</td>
<td style="text-align: left;">QC</td>
<td style="text-align: left;">2016-08-07</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FOX</td>
<td style="text-align: left;">989001000124022</td>
<td style="text-align: left;">R2</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.15</td>
<td style="text-align: left;">kg</td>
<td style="text-align: left;">healthy wild</td>
<td style="text-align: left;">UN</td>
<td style="text-align: left;">N</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Looking at these records, we can see that it is a Female fox on Santa Rosa Island that was observed 3 times during the same week in August 2016. The first capture it was tagged (<code>CaptureType</code> = New) and then it was re-tagged twice more.</p>
</section>
<section id="questions-to-try-out-1" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-try-out-1">Questions to Try Out</h3>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tagging Statistics
</div>
</div>
<div class="callout-body-container callout-body">
<p>How many different foxes have been tagged? If you look at `CaptureType’ you can also analyze how many foxes have been observed multiple times. What fraction of foxes were observed just once? How many unique foxes are on each of the two islands?</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Fox Life Story
</div>
</div>
<div class="callout-body-container callout-body">
<p>Find an ``interesting’’ fox that has been observed across a lengthy interval of time (multiple months and years). Investigate its record and write down a story about the life of this fox. For example: how did its weight, reproductive and vaccination status evolve over time? The aim of this Challenge is to convert the data/numbers into a verbal narrative/words.</p>
</div>
</div>
<section id="time-series" class="level4">
<h4 class="anchored" data-anchor-id="time-series">Time Series</h4>
<p>While above we considered the general <strong>population</strong> trends of how foxes are across the years, this evidence is not so conclusive because potentially it is about different foxes. A stronger analysis would directly track the same fox across time. <em>Time series</em>, where we put the date (in our case <code>TrapDate</code>) on the x-axis and the numeric variable of interest (say <code>Weight</code>) on the y-axis serve this purpose. To be interesting however, the time span needs to be long enough – it is not so interesting to make a time series for fox 989001000124022 that was only ever observed over a single week in 2016.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Fox Time Series
</div>
</div>
<div class="callout-body-container callout-body">
<p>Find foxes that are observed across multiple months/years and create time series plots for them. Report how your findings align or differ from the population-analysis we did in the Introduction.</p>
</div>
</div>
</section>
<section id="section" class="level4">
<h4 class="anchored" data-anchor-id="section"></h4>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>